apiVersion: v1
kind: Service
metadata:
  name: {{ include "closetai.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "closetai.name" . }}
    component: backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
