apiVersion: v1
kind: Secret
metadata:
  name: {{ include "closetai.fullname" . }}-secrets
type: Opaque
data:
  PERFECT_CORP_API_KEY: {{ .Values.secrets.perfectCorpApiKey | b64enc | quote }}
  PERFECT_CORP_API_SECRET: {{ .Values.secrets.perfectCorpApiSecret | b64enc | quote }}
  S3_KEY: {{ .Values.secrets.s3Key | b64enc | quote }}
  S3_SECRET: {{ .Values.secrets.s3Secret | b64enc | quote }}
  S3_BUCKET: {{ .Values.secrets.s3Bucket | b64enc | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc | quote }}
  ADMIN_TOKEN: {{ .Values.secrets.adminToken | b64enc | quote }}
