{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "closetai.fullname" . }}
  labels:
    {{ include "closetai.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "closetai.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- if .Values.autoscaling.externalMetric.enabled }}
    - type: External
      external:
        metric:
          name: {{ .Values.autoscaling.externalMetric.metricName }}
        target:
          type: Value
          value: "{{ .Values.autoscaling.externalMetric.targetValue }}"
{{- end }}
{{- end }}
