{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "closetai.fullname" . }}
  labels:
    {{ include "closetai.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{ include "closetai.selectorLabels" . | nindent 6 }}
{{- end }}
