apiVersion: v1
kind: Service
metadata:
  name: {{ include "closetai.fullname" . }}
  labels:
    {{ include "closetai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "closetai.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: metrics
      port: 9090
      targetPort: 9090
